# fly.toml app configuration file generated for thoughtsdb on 2023-07-13T21:59:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thoughtsdb"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[mounts]
source="thoughtsdb"
destination="/data"

[env]
  PORT = "5000"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 5000
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
