"""date

Revision ID: f419e0f94968
Revises: 6fbc4459f3d3
Create Date: 2023-07-28 14:55:41.747157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f419e0f94968'
down_revision = '6fbc4459f3d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date', sa.DateTime(), nullable=False, server_default='2023-07-28 14:59:37.270708'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date')
    # ### end Alembic commands ###
